services:
  container:
    image: ghcr.io/sourcequality/llmcord:latest
    container_name: llmcord
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app:ro
      - ./db:/opt/llmcord/db
